name: Deploy to GCP Compute Engine

on:
  push:
    branches:
      - main # Trigger deployment saat ada push ke branch main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy to GCP
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      run: |
        # Ganti <IP_PUBLIC_GCP> dengan IP Eksternal VM Compute Engine kamu
        ssh -o StrictHostKeyChecking=no ubuntu@35.197.132.113 << 'EOF'
          cd /var/www/mywebsite/runningCICD
          sudo git pull origin main
          # Restart Nginx untuk memastikan perubahan diterapkan
          sudo systemctl restart nginx
        EOF
